crowipmodule:
  host: xxx.xxx.xxx.xxx --> 192.168.0.1 
  port: 5002 --> standardport
  keepalive_interval: 60
  timeout: 20
  areas:
    1:
      name: 'Home' --> your own name
    2:
      name: 'None'  --> your own name
      code: '1234' --> your code is needed here
  outputs:
    3:
      name: 'Main Router'  --> your own name
    4:
      name: 'USV Restart'  --> your own name
  zones:
    1: --> up to 8 or 16 zones bases on your used Crow alarm system mainboard
      name: 'Entrance'  --> your own name
      type: 'motion'  --> your own type (motion,door, window)
    2:
      name: 'Terrace'
      type: 'door'
    3:
      name: 'Kitchen Window'
      type: 'window'
    4:
      name: 'Kitchen Door'
      type: 'door'
    5:
      name: 'Kitchen Motion'
      type: 'motion'
    6:
      name: 'Bedroom Motion'
      type: 'motion'
    7:
      name: 'Child Room'
      type: 'door'
    8:
      name: 'Child Window Wireless'
      type: 'window'
    9:
      name: 'Child PIR'
      type: 'motion'
    10:
      name: 'Den Motion'
      type: 'motion'
    11:
      name: 'Guest Motion'
      type: 'motion'
    12:
      name: 'Hall Motion'
      type: 'motion'
    13:
      name: 'Hobby Motion'
      type: 'motion'
    14:
      name: 'Bedroom Door'
      type: 'door'
    15:
      name: 'Guest Door'
      type: 'door'
    16:
      name: 'Exit Wireless'
      type: 'door'
